# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}" }

gem 'rack', '~> 2.2', '>= 2.2.3'
gem 'puma', '~> 4.3', '>= 4.3.5'
gem 'faker', '~> 2.13'

group :development do
  gem 'pry', '~> 0.13.1'
end